apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-api
  namespace: my-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodejs-api
  template:
    metadata:
      labels:
        app: nodejs-api
    spec:
      containers:
      - name: nodejs-api
        image: darshanaedirisinghe/nodejs-api:v1
        ports:
        - containerPort: 4001
        env:
        - name: NODE_ENV
          value: "production"
        - name: MONGO_URL
          value: "mongodb://mongodb:27017/entertainment"

---

apiVersion: v1
kind: Service
metadata:
  name: nodejs-service
  namespace: my-app
spec:
  type: NodePort
  selector:
    app: nodejs-api
  ports:
    - protocol: TCP
      port: 4001
      targetPort: 4001
      nodePort: 30001
