version: '3'

services:
  nodejs_api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4001:4001"
    depends_on:
      - mongodb

  mongodb:
    image: mongo
    ports:
      - "27017:27017"
